### ISSUE TITLE
there is something i wonder

### ISSUE THREAD

**Issue by WhiskyModz** [reveny/Android-Ptrace-Injector#1]
Is it useful to inject the lib into the game and run it? I don't understand exactly what it does, can you explain?

**Comment by reveny** [comment]
The program Injects a shared library into any process you specify. The steps to make it work are pretty simple and if you don't understand them, just don't use it.

**Comment by WhiskyModz** [comment]
@reveny i can make this a rooted injector using java

**Comment by WhiskyModz** [comment]
your new dll injector project looks good, I'm glad you made an injector using java, good job
