### ISSUE TITLE
MEMu emulator errors

### ISSUE THREAD

**Issue by ThunderMods** [reveny/Android-Ptrace-Injector#2]
I've trying to inject a shared library into a game. I use MEMu as emulator, it's x86 (nougat 7.0 / 32 bit). Sadly, it freezes my game and doesn't inject. Here is logcat:
ptrace_call mmap success. return value=FFFFFFFC, pc=C76EFA90
Remote Process Map Address: 0xfffffffc
Write Remote Memory error, MemoryAddr: 0xfffffffc, error:I/O error
writing /data/local/tmp/main to process failed
getRemoteFunctionAddr path: /system/bin/linker, localModuleAddr: 0xC7693000, remoteModuleAddr: 0xC76F0000, localModuleAddr: 0xC7693000, remoteFuncAddr: 0xC76F49C0
dlopen getRemoteFuncAddr: 0xc76f49c0
dlopen getRemoteFuncAddr: 0xc76f49c0
getRemoteFunctionAddr path: /system/bin/linker, localModuleAddr: 0xC7693000, remoteModuleAddr: 0xC76F0000, localModuleAddr: 0xC7693000, remoteFuncAddr: 0xC76F49C0
dlerror getRemoteFuncAddr: 0xc76f49c0
ptraceContinue success
ptrace call return value is 2943
Call dlopen Failed

**Comment by reveny** [comment]
Fixed
