### ISSUE TITLE
请添加 release 包  编译错误很烦人啊

### ISSUE THREAD

**Issue by wangchuanlai** [reveny/Android-Ptrace-Injector#7]
[arm64-v8a] Compile++      : Injector <= RevMemory.cpp
In file included from jni/RevMemory.cpp:9:
jni/Headers/NativeBridge.h:39:22: error: implicit instantiation of undefined template 'std::array<char, 92>'
        auto value = std::array<char, PROP_VALUE_MAX>();
                     ^
/Users/wangnima/Library/Android/sdk/ndk/25.1.8937393/sources/cxx-stl/llvm-libc++/include/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
1 error generated.

**Comment by reveny** [comment]
Use NDK 26.x.xxxx. I recommend using 26.1.10909125
Compilation works fine there
